services:
  backend:
    build:
      context: ./backend
    container_name: calendar-backend
    restart: always
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8000"
      MODEUS_USERNAME: test
      MODEUS_PASSWORD: test
    volumes:
      - ./backend:/app/
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./frontend
    container_name: calendar-frontend
    restart: always
    ports:
      - 3000:80

