services:
  api: &main_app
    ports:
      - "8000:8000"
    build:
      context: backend/
      dockerfile: Dockerfile
    image: yet_another_calendar:${YET_ANOTHER_CALENDAR_VERSION:-latest}
    restart: always
    volumes:
      - ./backend:/app/src/
    env_file:
      - backend/.env
    depends_on:
      redis:
        condition: service_healthy
    environment:
      YET_ANOTHER_CALENDAR_HOST: 0.0.0.0
      YET_ANOTHER_CALENDAR_REDIS_HOST: yet_another_calendar-redis
      LOGURU_DIAGNOSE: "False"

  redis:
    image: redis:latest
    hostname: "yet_another_calendar-redis"
    restart: always
    volumes:
      - redis_data:/data
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  frontend:
    build:
      context: ./frontend
      target: dev-run
    container_name: calendar-frontend
    restart: always
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "3000:3000"

volumes:
  redis_data:
