services:
  backend:
    build:
      context: ./backend
    container_name: calendar-backend
    restart: always
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/
    ports:
      - 8000:8000
