[tool.poetry]
name = "calendarit"
version = "0.1.0"
description = ""
authors = ["Popov, Ivan <ma1n.py@yandex.ru>"]
license = "GNU"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
undetected-chromedriver = "^3.5.5"
environs = "^11.0.0"
jwt = "^1.3.1"
httpx = {version = ">=0.19.0", extras = ["http2"]}
beautifulsoup4 = ">=4.10.0,<4.11.0"
blacksheep = {version = ">=2.0.0,<2.1.0", extras = ["full"]}
blacksheep-cli = "^0.0.4"
uvicorn = "0.22.0"
pydantic-settings = "^2.5.2"
markupsafe = "2.1.3"
pydantic = "^2.9.2"
mypy = "^1.11.2"
types-requests = "^2.32.0.20240914"
types-beautifulsoup4 = "^4.12.0.20240907"
wemake-python-styleguide = "^0.19.2"
isort = "^5.13.2"
black = "^24.8.0"
lxml = "^5.3.0"
python-multipart = "^0.0.10"
pyyaml = "^6.0.2"


[tool.poetry.group.dev.dependencies]
ipython = "^8.27.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
strict = true
ignore_missing_imports = true
allow_subclassing_any = true
allow_untyped_calls = true
pretty = true
show_error_codes = true
implicit_reexport = true
allow_untyped_decorators = true
warn_return_any = false
warn_no_return = false