[tool.poetry]
name = "calendarit"
version = "0.1.0"
description = ""
authors = ["Popov, Ivan <ma1n.py@yandex.ru>"]
license = "GNU"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
undetected-chromedriver = "^3.5.5"
environs = "^11.0.0"
jwt = "^1.3.1"
httpx = {version = ">=0.19.0", extras = ["http2"]}
beautifulsoup4 = ">=4.10.0,<4.11.0"
blacksheep = {version = ">=2.0.0,<2.1.0", extras = ["full"]}
blacksheep-cli = "^0.0.4"
uvicorn = "0.22.0"
pydantic-settings = "^2.5.2"
markupsafe = "2.1.3"
pydantic = "^2.9.2"
mypy = "^1.11.2"
types-requests = "^2.32.0.20240914"
types-beautifulsoup4 = "^4.12.0.20240907"
black = "^24.8.0"
lxml = "^5.3.0"
python-multipart = "^0.0.10"
pyyaml = "^6.0.2"
flake8-docstrings = "^1.7.0"
ruff = "^0.6.7"
pyflakes = "^3.2.0"
pycodestyle = "^2.12.1"
flake8-debugger = "^4.1.2"
flake8-logging = "^1.6.0"
flake8-print = "^5.0.0"
pep8-naming = "^0.14.1"
pylint = "^3.3.1"


[tool.poetry.group.dev.dependencies]
ipython = "^8.27.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
strict = true
ignore_missing_imports = true
allow_subclassing_any = true
allow_untyped_calls = true
pretty = true
show_error_codes = true
implicit_reexport = true
allow_untyped_decorators = true
warn_return_any = false
warn_no_return = false

[tool.ruff]
lint.select = [
    "A",  # prevent using keywords that clobber python builtins
    "N",  # pep8-naming
    "B",  # bugbear: security warnings
    "E",  # pycodestyle
    "F",  # pyflakes
    "ISC",  # implicit string concatenation
    "UP",  # alert you when better syntax is available in your python version
    "RUF",  # the ruff developer's own rules

    "T20",  # flake8-print
    "T10",  # flake8-debugger
    "LOG",  # flake8-logging
    "COM",  # flake8-logging
    "ASYNC",  # flake8-async
    "ANN",  # flake8-annotations
    "PL",  # Pylint
]
line-length = 119
lint.ignore = [
    "ANN101",
    "ANN401",
    "ANN102"
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 119
